Clarifications, more active voice, American spellings
thegooddocsproject/templates pull request #153
Opened 2020-08-17 19:13 UTC by Technicalleigh

> __ALL Pull-Requests require an associated [Issue](https://github.com/thegooddocsproject/templates/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) as documented in [How to contribute](https://github.com/thegooddocsproject/templates/blob/master/contribute.md#contributing).__

## Purpose / why

> _**Replace this text** - Restate the purpose/justification of this work and include links to the Issue inside of the purpose/why._

## What changes were made?

> _**Replace this text** - State clearly the direct additions or modifications made in this change-request._

## Verification

> _**Replace this text** - Document the details that help a reviewer understand what steps or actions should be taken in-order to verify the work is completed and satisfies the initial scope of work._

---

## Checklist

> __Pull-request reviewer__ should ensure the following

* [ ] Are issues linked correctly?
* [ ] Is this PR labeled correctly?
* [ ] If template updates: do they align with [developers.google.com/style/](https://developers.google.com/style/)?
* [ ] Did the PR receive at least one :+1: and no :-1: from core-maintainers?
* [ ] On merging, did you complete the merge using [keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-to-an-issue)?

2020-08-19 00:10 UTC, Loquacity requested changes

2020-08-19 00:10 UTC, Loquacity commented on how-to/about-how-to.md
> +Creating a good overview comes down to thinking about will use the doc:
```suggestion
Creating a good overview comes down to thinking about who will be reading the document:
```

2020-08-19 00:10 UTC, Loquacity commented on how-to/about-how-to.md
> +Whenever possible, include links to procedures or information, or give your audience tips about how to get whatever they need.
```suggestion
Describe what the reader needs to know or have before following this how-to. Prerequisites can include other articles or information the reader needs to understand first. This list can also include technical dependencies, such as requiring an internet connection. By stating the requirements up-front, you prevent your audience from having a bad experience with your how-to. Whenever possible, include links to procedures or information, or give your audience tips about how to get whatever they need.
```

2020-08-19 00:10 UTC, Loquacity commented on how-to/about-how-to.md
> +Whenever possible, include links to procedures or information, or give your audience tips about how to get whatever they need.
Not entirely certain what's happening with the line breaks here.

2020-11-04 20:27 UTC, aidanatwork commented on how-to/about-how-to.md
> +* You need to have a list of favorites before you can manage them. For more information about favourites lists, see #Create_Favorites.
We still need to change to the American spelling for "favorites" in the last instance at the end of this sentence.

2020-11-05 00:56 UTC, Loquacity commented
This has picked up a bunch of conflicts with my PR#96 Would you like to me go through and fix the conflicts, or should we close this PR without merging?

2020-12-01 20:32 UTC, aidanatwork commented
> This has picked up a bunch of conflicts with my PR #162 Would you like to me go through and fix the conflicts, or should we close this PR without merging?

@Loquacity Please go ahead and try to resolve the conflicts. If you are getting stuck, feel free to reach out to me or Morgan Craft to help further.

2020-12-01 23:20 UTC, Loquacity commented
Merge conflicts resolved. Ready to merge once others are happy.

2020-12-01 23:20 UTC, Loquacity approved these changes

2021-01-23 03:54 UTC, merged